version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'injection'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'TZ9Mdu.xekb('
    ports:
      - "3306:3306"
